// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnrBXmxejowFVP3b8BWPe0kemE3rHV4Pg',
    appId: '1:920401170423:web:7115c4497151f1088ee8f2',
    messagingSenderId: '920401170423',
    projectId: 'portfolio-app-a1417',
    authDomain: 'portfolio-app-a1417.firebaseapp.com',
    storageBucket: 'portfolio-app-a1417.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5UInzDYrTQOWmDfMuoyAa41yM4UoiuvU',
    appId: '1:920401170423:android:46864b9c3ae4de948ee8f2',
    messagingSenderId: '920401170423',
    projectId: 'portfolio-app-a1417',
    storageBucket: 'portfolio-app-a1417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5U5R-ZeGns5VFPkWPBwDwFzjc9gj0SdM',
    appId: '1:920401170423:ios:f599057ad617af2f8ee8f2',
    messagingSenderId: '920401170423',
    projectId: 'portfolio-app-a1417',
    storageBucket: 'portfolio-app-a1417.firebasestorage.app',
    iosBundleId: 'com.codingliquids.paulinaKnop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnrBXmxejowFVP3b8BWPe0kemE3rHV4Pg',
    appId: '1:920401170423:web:c62932f3e07b65598ee8f2',
    messagingSenderId: '920401170423',
    projectId: 'portfolio-app-a1417',
    authDomain: 'portfolio-app-a1417.firebaseapp.com',
    storageBucket: 'portfolio-app-a1417.firebasestorage.app',
  );
}
